# Generated by Django 4.1.6 on 2023-02-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ezhednevnik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zadachi",
                    models.CharField(help_text="Название задачи", max_length=150),
                ),
            ],
        ),
    ]
