# Generated by Django 4.1.6 on 2023-02-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("t_list", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ezhednevnik",
            name="time_nach",
            field=models.DateTimeField(auto_now=True, help_text="Время начала"),
        ),
    ]
