# Generated by Django 4.1.6 on 2023-02-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("t_list", "0002_ezhednevnik_time_nach"),
    ]

    operations = [
        migrations.AddField(
            model_name="ezhednevnik",
            name="active_switch",
            field=models.BooleanField(default=True, help_text="Статус задачи"),
        ),
    ]
