# Generated by Django 4.1.6 on 2023-02-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("t_list", "0003_ezhednevnik_active_switch"),
    ]

    operations = [
        migrations.AddField(
            model_name="ezhednevnik",
            name="status",
            field=models.CharField(
                default="В работе", help_text="Статус задачи", max_length=150
            ),
        ),
    ]
