# Generated by Django 4.1.6 on 2023-02-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("t_list", "0004_ezhednevnik_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ezhednevnik",
            name="time_zav",
            field=models.DateTimeField(auto_now=True, help_text="Время завершения"),
        ),
    ]
